services:
  - type: web
    name: vsrglabs-web
    env: python
    plan: free
    buildCommand: poetry install --no-root
    startCommand: |
      poetry run python manage.py collectstatic --noinput &&
      poetry run python manage.py migrate &&
      poetry run daphne -b 0.0.0.0 -p 8000 django_project.asgi:application
    envVars:
      - key: DJANGO_ALLOWED_HOSTS
        value: vsrglabs-web.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_sJ0CWtnkF6dN@ep-odd-band-a84fg8rc-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
