services:
  - type: web
    name: vsrglabs-web
    env: python
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn django_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
