services:
  - type: web
    name: vsrglabs-web
    env: python
    plan: free
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn django_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_sJ0CWtnkF6dN@ep-odd-band-a84fg8rc-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true

