services:
  - type: web
    name: vsrglabs-web
    env: python
    plan: free
    buildCommand: "./manage.py collectstatic --noinput"
    startCommand: "gunicorn django_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: django-db
    databaseName: django_db
    user: django_user

