# Generated by Django 5.2.2 on 2025-06-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamemap",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="gamemap",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gamemap",
            name="likes",
        ),
        migrations.AlterField(
            model_name="vote",
            name="game_map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="main.gamemap",
            ),
        ),
    ]
