# Generated by Django 5.2.2 on 2025-06-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_gamemap_dislikes_remove_gamemap_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemap",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamemap",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
